version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "text to output here" > output.txt
      - save_cache:
          key: v1-my-project-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

  say-world:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "say world"
          command: cat ~/output.txt
      - restore_cache:
          keys:
            - v1-my-project-{{ checksum "project.clj" }}
            - v1-my-project-

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello
