version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "save data to file"
          command: echo "text to output here" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  say-world:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: 
          name: "read file saved from other job"
          command: cat ~/output.txt
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello
